apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongosh-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: storage-class-xfs